const getters = {
  sidebar: state => state.app.sidebar,
  device: state => state.app.device,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  username: state => state.user.username,
  roles: state => state.user.roles,
  weight: state => state.user.weight,
  age: state => state.user.age,
  stature: state => state.user.stature,
  position: state => state.user.position,
  sex: state => state.user.sex,
  id: state => state.user.id,
  football_tream: state => state.user.football_tream,
  pass_football: state => state.user.pass_football,
  hotshot: state => state.user.hotshot,
  speed_num: state => state.user.speed_num,
  join_time: state => state.user.join_time,
  sprint_distance: state => state.user.sprint_distance,
  run_distance: state => state.user.run_distance,
  sprint_num: state => state.user.sprint_num,
  heart_avg: state => state.user.heart_avg,
  phone: state => state.user.phone,
  password: state => state.user.password,
}
export default getters
